import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { z } from 'zod';

const ConflictValueSchema = z.object({
  value: z.string().min(1),
  source: z.string().optional(),
  weight: z.number().min(0).max(1).optional(),
  note: z.string().optional(),
});

const ConflictEntrySchema = z.object({
  field: z.string().regex(
    /^(birth|death)\.(date|place)$|^marriage\.[A-Za-z0-9_-]+\.(date|place)$/,
    "field must be one of birth.date, birth.place, death.date, death.place, or marriage.<famId>.date|place",
  ),
  values: z.array(ConflictValueSchema).min(2),
  note: z.string().optional(),
  resolved: z.boolean().optional(),
});

export type ConflictValue = z.infer<typeof ConflictValueSchema>;
export type ConflictEntry = z.infer<typeof ConflictEntrySchema>;

/**
 * Load conflict entries for a record from `<genealogyDir>/conflicts/<record>.yml`.
 * Each entry is validated independently — a typo'd field path on entry #2
 * does not silently drop entries #1 and #3. Invalid entries are skipped and
 * logged to stderr so the user can see why a hand-written conflict isn't
 * rendering.
 *
 * The conflicts directory is hand-edited (or future CLI-driven). It is *not*
 * regenerated by `wai sync-gedcom`, so entries survive re-derivation. This is
 * intentional: conflicts are user judgements about evidence, not facts derived
 * from the GEDCOM input.
 */
export function loadConflicts(
  genealogyDir: string,
  record: string,
  log: (msg: string) => void = msg => console.error(msg),
): ConflictEntry[] {
  if (!/^I\d+$/.test(record)) return [];
  const path = join(genealogyDir, 'conflicts', `${record}.yml`);
  if (!existsSync(path)) return [];
  const raw = yaml.load(readFileSync(path, 'utf-8'));
  if (!raw || typeof raw !== 'object') return [];
  const arr = (raw as { conflicts?: unknown }).conflicts;
  if (!Array.isArray(arr)) return [];

  const valid: ConflictEntry[] = [];
  for (let i = 0; i < arr.length; i++) {
    const result = ConflictEntrySchema.safeParse(arr[i]);
    if (result.success) {
      valid.push(result.data);
      continue;
    }
    const issues = result.error.issues
      .map(iss => `${iss.path.join('.') || '<root>'}: ${iss.message}`)
      .join('; ');
    log(`[whoami] conflicts/${record}.yml entry ${i} ignored — ${issues}`);
  }
  return valid;
}
