/**
 * Pure helpers for the `## Research notes` section of a talk-page body.
 *
 * - Each bullet may carry a trailing HTML comment that holds the note's
 *   stable id, author, kind (human/agent), and timestamps for create,
 *   edit (latest only), and soft-delete. Bullets without a trailer are
 *   "legacy" notes — parsed read-only with a synthetic id and `(unknown)`
 *   author.
 * - All functions are pure: id and `now` come from the caller, so tests
 *   stay deterministic without injecting a clock or RNG.
 */

export type NoteKind = 'human' | 'agent';

export interface Note {
  id: string;
  date: string;             // YYYY-MM-DD (the day heading)
  text: string;             // bullet prose, sans "- " prefix and trailer (multi-line preserved)
  by: string;               // "(unknown)" for legacy
  kind: NoteKind;           // legacy → 'human'
  createdAt: string | null; // null for legacy
  editedAt: string | null;
  editedBy: string | null;
  deletedAt: string | null;
  deletedBy: string | null;
  isLegacy: boolean;        // derived: true iff bullet has no trailer
}

export interface NewNoteInput {
  id: string;       // generated by caller
  text: string;
  by: string;
  kind: NoteKind;
  createdAt: string; // ISO-8601 UTC
}

export class NoteNotFoundError extends Error {
  constructor(public readonly noteId: string) {
    super(`note not found: ${noteId}`);
    this.name = 'NoteNotFoundError';
  }
}

export class NoteDeletedError extends Error {
  constructor(public readonly noteId: string) {
    super(`note is deleted: ${noteId}`);
    this.name = 'NoteDeletedError';
  }
}

export class NoteAlreadyDeletedError extends Error {
  constructor(public readonly noteId: string) {
    super(`note is already deleted: ${noteId}`);
    this.name = 'NoteAlreadyDeletedError';
  }
}

const SECTION_RE = /^## Research notes\s*$/;
const DAY_HEADING_RE = /^### (\d{4}-\d{2}-\d{2})\s*$/;
const BULLET_START_RE = /^- (.*)$/;
const TRAILER_RE = /^\s*<!--\s*note\s+(.+?)\s*-->\s*$/;

/**
 * Return every note in the section, newest day first, in-document order
 * within a day. Bullets without a trailer are returned as legacy
 * (synthetic deterministic id, `by="(unknown)"`, `createdAt=null`).
 */
export function parseResearchNotes(body: string): Note[] {
  const lines = body.split('\n');
  const sectionStart = lines.findIndex((l) => SECTION_RE.test(l));
  if (sectionStart === -1) return [];

  let sectionEnd = lines.length;
  for (let i = sectionStart + 1; i < lines.length; i++) {
    if (/^## /.test(lines[i]!)) { sectionEnd = i; break; }
  }

  const notes: Note[] = [];
  let currentDate = '';
  let positionInDay = 0;

  let i = sectionStart + 1;
  while (i < sectionEnd) {
    const line = lines[i]!;
    const dayMatch = DAY_HEADING_RE.exec(line);
    if (dayMatch) {
      currentDate = dayMatch[1]!;
      positionInDay = 0;
      i++;
      continue;
    }
    const bulletMatch = BULLET_START_RE.exec(line);
    if (!bulletMatch || !currentDate) {
      i++;
      continue;
    }
    // Bullet block runs from this line through the next bullet, day
    // heading, blank-then-non-continuation, or section end.
    const headText = bulletMatch[1]!;
    const blockLines: string[] = [headText];
    let trailerAttrs: string | null = null;
    let j = i + 1;
    while (j < sectionEnd) {
      const nl = lines[j]!;
      if (BULLET_START_RE.test(nl)) break;
      if (DAY_HEADING_RE.test(nl)) break;
      if (/^## /.test(nl)) break;
      // Blank line is part of the block only if continuation follows.
      if (nl === '') {
        const k = j + 1;
        if (k >= sectionEnd) break;
        const peek = lines[k]!;
        if (peek.startsWith('  ') || TRAILER_RE.test(peek)) {
          blockLines.push('');
          j++;
          continue;
        }
        break;
      }
      const trailerMatch = TRAILER_RE.exec(nl);
      if (trailerMatch) {
        trailerAttrs = trailerMatch[1]!;
        j++;
        continue;
      }
      // Continuation line: drop the two-space indent.
      blockLines.push(nl.startsWith('  ') ? nl.slice(2) : nl);
      j++;
    }

    const text = blockLines.join('\n').replace(/\s+$/, '');
    const attrs = trailerAttrs ? parseTrailerAttrs(trailerAttrs) : null;
    if (attrs?.id) {
      notes.push({
        id: attrs.id,
        date: currentDate,
        text,
        by: attrs.by ?? '(unknown)',
        kind: (attrs.kind === 'agent' ? 'agent' : 'human'),
        createdAt: attrs.at ?? null,
        editedAt: attrs.editedAt ?? null,
        editedBy: attrs.editedBy ?? null,
        deletedAt: attrs.deletedAt ?? null,
        deletedBy: attrs.deletedBy ?? null,
        isLegacy: false,
      });
    } else {
      notes.push({
        id: `n_legacy_${currentDate}_${positionInDay}`,
        date: currentDate,
        text,
        by: '(unknown)',
        kind: 'human',
        createdAt: null,
        editedAt: null,
        editedBy: null,
        deletedAt: null,
        deletedBy: null,
        isLegacy: true,
      });
    }
    positionInDay++;
    i = j;
  }
  return notes;
}

function parseTrailerAttrs(s: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const tok of s.split(/\s+/)) {
    const eq = tok.indexOf('=');
    if (eq === -1) continue;
    out[tok.slice(0, eq)] = tok.slice(eq + 1);
  }
  return out;
}

export interface AppendOptions {
  /** Day heading to file under (YYYY-MM-DD). Defaults to UTC date of input.createdAt. */
  date?: string;
}

/**
 * Append a single research note to the `## Research notes` section,
 * newest-day-first chronology preserved. Pure: returns a new body string.
 */
export function appendResearchNote(
  body: string,
  input: NewNoteInput,
  options: AppendOptions = {},
): string {
  const date = options.date ?? input.createdAt.slice(0, 10);
  const block = formatBulletBlock(input);
  const lines = body.split('\n');

  const sectionIdx = lines.findIndex((l) => SECTION_RE.test(l));

  if (sectionIdx === -1) {
    const trimmed = body.replace(/\s+$/, '');
    const sep = trimmed.length === 0 ? '' : '\n\n';
    return `${trimmed}${sep}## Research notes\n\n### ${date}\n${block}\n`;
  }

  let endIdx = lines.length;
  for (let i = sectionIdx + 1; i < lines.length; i++) {
    if (/^## /.test(lines[i]!)) { endIdx = i; break; }
  }

  const todayHeading = `### ${date}`;
  let todayIdx = -1;
  for (let i = sectionIdx + 1; i < endIdx; i++) {
    if (lines[i] === todayHeading) { todayIdx = i; break; }
  }

  if (todayIdx !== -1) {
    let blockEnd = endIdx;
    for (let i = todayIdx + 1; i < endIdx; i++) {
      if (/^### /.test(lines[i]!)) { blockEnd = i; break; }
    }
    let insertAt = blockEnd;
    while (insertAt > todayIdx + 1 && lines[insertAt - 1] === '') insertAt--;
    lines.splice(insertAt, 0, ...block.split('\n'));
    return lines.join('\n');
  }

  let insertAt = sectionIdx + 1;
  while (insertAt < endIdx && lines[insertAt] === '') insertAt++;

  const inserted: string[] = [todayHeading, ...block.split('\n')];
  if (insertAt < endIdx && lines[insertAt] !== '') inserted.push('');
  if (lines[sectionIdx + 1] !== '') inserted.unshift('');
  lines.splice(insertAt, 0, ...inserted);
  return lines.join('\n');
}

function formatBulletBlock(input: NewNoteInput): string {
  const trimmed = input.text.replace(/\s+$/, '').replace(/^\n+/, '');
  const head = trimmed === '' ? '(empty)' : trimmed.split('\n')[0]!;
  const tail = trimmed === ''
    ? []
    : trimmed.split('\n').slice(1).map((l) => (l.length === 0 ? '' : `  ${l}`));
  const trailer = `  ${formatTrailer(input)}`;
  return [`- ${head}`, ...tail, trailer].join('\n');
}

function formatTrailer(input: NewNoteInput): string {
  return `<!-- note id=${input.id} by=${input.by} kind=${input.kind} at=${input.createdAt} -->`;
}

/**
 * Rewrite the prose of an existing note (matched by id), updating the
 * trailer's `editedAt`/`editedBy` to the latest edit. Throws if the id
 * is unknown or the note is soft-deleted (caller must restore first).
 */
export function editResearchNote(
  body: string,
  id: string,
  newText: string,
  editor: string,
  editedAt: string,
): string {
  const span = findBulletSpan(body, id);
  if (!span) throw new NoteNotFoundError(id);
  if (span.attrs.deletedAt) throw new NoteDeletedError(id);
  span.attrs.editedAt = editedAt;
  span.attrs.editedBy = editor;
  return spliceBulletBlock(body, span, newText, span.attrs);
}

interface BulletSpan {
  startLine: number;        // index of "- ..." line
  endLineExclusive: number; // first line after the bullet's block (incl trailer)
  attrs: TrailerAttrs;
  trailerLineIndex: number; // index of trailer line within the body
}

interface TrailerAttrs {
  id: string;
  by: string;
  kind: NoteKind;
  at: string;
  editedAt?: string;
  editedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
}

function findBulletSpan(body: string, id: string): BulletSpan | null {
  const lines = body.split('\n');
  const sectionStart = lines.findIndex((l) => SECTION_RE.test(l));
  if (sectionStart === -1) return null;
  let sectionEnd = lines.length;
  for (let i = sectionStart + 1; i < lines.length; i++) {
    if (/^## /.test(lines[i]!)) { sectionEnd = i; break; }
  }
  for (let i = sectionStart + 1; i < sectionEnd; i++) {
    if (!BULLET_START_RE.test(lines[i]!)) continue;
    const start = i;
    let trailerLine = -1;
    let j = i + 1;
    while (j < sectionEnd) {
      const nl = lines[j]!;
      if (BULLET_START_RE.test(nl)) break;
      if (DAY_HEADING_RE.test(nl)) break;
      if (/^## /.test(nl)) break;
      if (nl === '') {
        const k = j + 1;
        if (k >= sectionEnd) break;
        const peek = lines[k]!;
        if (peek.startsWith('  ') || TRAILER_RE.test(peek)) { j++; continue; }
        break;
      }
      if (TRAILER_RE.test(nl)) { trailerLine = j; j++; continue; }
      j++;
    }
    if (trailerLine === -1) { i = j - 1; continue; }
    const m = TRAILER_RE.exec(lines[trailerLine]!)!;
    const attrs = parseTrailerAttrs(m[1]!) as Partial<TrailerAttrs>;
    if (attrs.id !== id) { i = j - 1; continue; }
    return {
      startLine: start,
      endLineExclusive: j,
      attrs: {
        id: attrs.id,
        by: attrs.by ?? '(unknown)',
        kind: (attrs.kind === 'agent' ? 'agent' : 'human'),
        at: attrs.at ?? '',
        editedAt: attrs.editedAt,
        editedBy: attrs.editedBy,
        deletedAt: attrs.deletedAt,
        deletedBy: attrs.deletedBy,
      },
      trailerLineIndex: trailerLine,
    };
  }
  return null;
}

function spliceBulletBlock(
  body: string,
  span: BulletSpan,
  newText: string,
  attrs: TrailerAttrs,
): string {
  const lines = body.split('\n');
  const trimmed = newText.replace(/\s+$/, '').replace(/^\n+/, '');
  const head = trimmed === '' ? '(empty)' : trimmed.split('\n')[0]!;
  const tail = trimmed === ''
    ? []
    : trimmed.split('\n').slice(1).map((l) => (l.length === 0 ? '' : `  ${l}`));
  const trailer = `  ${serializeTrailer(attrs)}`;
  const next = [`- ${head}`, ...tail, trailer];
  lines.splice(span.startLine, span.endLineExclusive - span.startLine, ...next);
  return lines.join('\n');
}

function serializeTrailer(attrs: TrailerAttrs): string {
  const parts = [
    `id=${attrs.id}`,
    `by=${attrs.by}`,
    `kind=${attrs.kind}`,
    `at=${attrs.at}`,
  ];
  if (attrs.editedAt) parts.push(`editedAt=${attrs.editedAt}`);
  if (attrs.editedBy) parts.push(`editedBy=${attrs.editedBy}`);
  if (attrs.deletedAt) parts.push(`deletedAt=${attrs.deletedAt}`);
  if (attrs.deletedBy) parts.push(`deletedBy=${attrs.deletedBy}`);
  return `<!-- note ${parts.join(' ')} -->`;
}

/**
 * Return the markdown body of the `## Research notes` section
 * (without the `## Research notes` heading itself), or an empty
 * string if no such section exists. Used by the renderer to surface
 * the section on the article page without re-parsing the heading.
 */
export function extractResearchNotesSection(body: string): string {
  const lines = body.split('\n');
  const start = lines.findIndex((l) => /^## Research notes\s*$/.test(l));
  if (start === -1) return '';
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^## /.test(lines[i]!)) {
      end = i;
      break;
    }
  }
  let bodyStart = start + 1;
  while (bodyStart < end && lines[bodyStart] === '') bodyStart++;
  return lines.slice(bodyStart, end).join('\n').replace(/\s+$/, '');
}

